#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
set -e
echo ''

info () {
    printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
	printf "\r [ \033[0;33m??\033[0m] $1\n"
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

link_file () {
	local src=$1 dst=$2

	ln -s $1 $2
	success "Linked $1 to $2"
}

install_dotfiles () {
	for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
	do
        echo "Checking for existing .$(basename ${src%.symlink}) symlink..."
        if [ -e "${HOME}/.$(basename ${src%.symlink})" ]; then
            echo "symlink for ${src} exists"
        else
		    dst="$HOME/.$(basename "${src%.*}")"
		    link_file "$src" "$dst"
        fi
	done
}

add_cron () {
    local frequency="*/15 * * * *"
    local command=$1
    local job="$frequency $command"
    cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -
}

add_line () {
    local command=$1
    local job="$command"
    cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -
}

ln $DOTFILES_ROOT/tmux/tmux.conf.symlink ~/.tmux.conf && success "symlink for .tmux.conf"

if ! [ -f /usr/local/bin/airport ]
    then
        sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport
        success "symlink for airport created"
else 
    info "symlink for airport already exists"
fi

add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    if [[ $? -eq 0 ]]
        then
          success "$PATH added to crontab"
        else
          info "ERROR $PATH could not be added to crontab"
    fi

add_cron "speedtest-cli --simple > ~/bin/bandwidth.log"
    if [[ $? -eq 0 ]]
        then
            success "crontab created for speedtest cli --simple"
        else
            info "ERROR: crontab could not be created for speedtest cli --simple"
    fi

add_cron "speedtest-cli --json > ~/bin/bandwidth.json"
    if [[ $? -eq 0 ]]
        then
            success "crontab created for speedtest-cli --json"
        else
            info "ERROR: crontab could not be created for speedtest-cli --json"
    fi

echo "Running speedtest-cli for tmux status bar"
speedtest-cli --simple > ~/bin/bandwidth.log
success "speedtest-cli bandwidth.log created"

speedtest-cli --json > ~/bin/bandwidth.json
success "speedtest-cli bandwidth.json created"

install_dotfiles
